### PR TITLE
[wip] Modify Dockerfile to derive from Ubuntu DinD Dockerfile.

### PR DESCRIPTION
**Pull request by ssk2**

### CODE REVIEW

**Comment by tobilg** [comment]
Thanks for the PR! I have some remarks about it:
- Why using the Jenkins DinD image? There seem to be a lot of unnecessary packages installed (Java etc.), see
- Using DinD for CI is somehow discouraged, even by Docker people, see http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ ("The solution")
- Running `dig srv _instance._gitlab._tcp.marathon.mesos` returns nothing in my DC/OS 1.8 GA cluster, even it the service `gitlab` is running. Are you sure this is the right notation?

**Comment by ssk2** [comment]
Hey @tobilg - my apologies! Was meant to target this PR against the master branch of our repo, not yours.

This is still a WIP implementation for https://github.com/mesosphere/universe/pull/746. We're still trying to get it to work :). The dig line is problematic, I need to debug that.  Re-used the Jenkins DinD one for the sake of convenience, once we get it working, we'll re-create it (or work with the GitLab team to provide a better alternative).

We prefer DinD on the recommendation of the Mesos team, to avoid resource leaks. @rji has a good writeup here: https://github.com/mesosphere/jenkins-dind-agent/issues/1. We're working on a solution to avoid having to do Docker in Docker, which is probably a few months out. For now this is a solution that works well on small to medium size clusters across varying operating systems.

**Comment by tobilg** [comment]
Thanks for the feedback. I got both shell and docker executors to run now on our DC/OS 1.8 cluster with the GitLab Universe package, so I'm happy :-)

I understand the _resource isolation_ issues with the approach I'm currently using. So far, I personally didn't face problems (yet) during the 5 months we're running our builds this way. I think the _Orphaned containers_ issue is not the case with GitLab, but I'm not 100% sure.

I'll try the DinD approach as well, but I have some fears that the non-working Docker caching has some downsides regarding build speeds and disk space usage.

Anyway, if I can help you with the package, please let me know.

**Comment by ssk2** [comment]
GitLab is probably more sensible about cleaning up running Docker containers than Jenkins users may be! We have some ideas about how to get around the caching problems but you're right in that it is slower.

**Comment by ssk2** [comment]
Will definitely be getting in touch once the package is out to get your input :)

**Pull request closed without merging**
